name: Deploy to production
on:
  push:
    branches:
      - deploy-action

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: build
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.PROD_SERVER }}
          username: ${{ secrets.PROD_SERVER_USERNAME}}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          script: |
            cd ~/stagetool-ui
            git reset --hard HEAD
            git pull
            docker build . -t stagetool-ui
            docker compose up -d
