name: Deploy to production
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: build
        uses: actions/ssh-action@v1.0.3

        with:
          host: ${{ secrets.PROD_SERVER }}
          username: ${{ secrets.PROD_SERVER_USERNAME}}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          script: whoami
